---
name: "Packer Image"

on:
  push:
    branches:
      - prod
    
jobs:
    
  build:

    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_SECRET_KEY }}
      AWS_ACCESS_REGION: ${{ secrets.PROD_ACCESS_REGION }}
      packer_version: "1.9.4"

    steps:

      - name: "Repository Checkout"
        uses: actions/checkout@v3

      - name: "Packer Installation"
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.packer_version }}

      - name: "Packer Init"
        run: packer init  .
        
      - name: "Packer Validate"
        run: packer validate  -var-file="prod.pkrvars.hcl" .
        
      - name: "Format Packer Template"
        run: packer fmt .
        
      - name: "Packer build Image"
        run: packer build  -var-file="prod.pkrvars.hcl" .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_SECRET_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.PROD_ACCESS_REGION }}
